### ISSUE TITLE
EhCachePlugin does not work with EhCache versions > 2.6.8

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#93]
EhCachePlugin tries to call a method that does not longer exist in EhCache

    Caused by: java.lang.NoSuchMethodError: net.sf.ehcache.Cache.setStatisticsEnabled(Z)V
	at org.stagemonitor.ehcache.EhCachePlugin.initializePlugin(EhCachePlugin.java:46)

In fact this method was removed from 2.6.9 onwards

**Comment by felixbarny** [comment]
I have checked this. In ehcache 2.6.11 this method is still there. Which version are you using? Do you have a source that this method was removed?

**Comment by yacota** [comment]
You are right still there in 2.6.11 .... I've checked so many sources that my IDE got confused,  I swear:) 
But it is removed in 2.7.8, 2.8.6, ...

**Comment by Meilarium** [comment]
Hi,
I'm a Spring Boot user and i'm very interesting by this fix.
Thanks,
Bruno

**Comment by felixbarny** [comment]
Thx for the bump. This is definitely due.

**Comment by get2parag** [comment]
+1 waiting for this to be resolved. 
Spring boot user, using stagemonitor and ehcache in my application.
